### PR TITLE
issue #45: Use alternative delimiter to make pgn json-compliant

### LINKED ISSUE #45: rest client body for post to /games
Nice app. Exactly what I was looking for, and mostly in my wheelhouse to work with. I am having issues in posting new games. I've tries some variations of the message body. If I have \n in the json body, that fails to parse so I get 400 error. If I do not have \n, then the game pgn does not parse so I get a 500 error. I reviewed the tests but there are no full json body's sent in them. Any ideas?

ps. I'm trying to load games that I played in chess.com to analyze which openings are most difficult for me so I can target which ones I spend more time learning.

p.s.s. I don't think you are actively supporting this so I may fork and try my own solution.

400 Error:
```
{
    "data": {
        "pgn": "[Event \"Live Chess\"]
[Site \"Chess.com\"]
[Date \"2021.03.18\"]
[Round \"-\"]
[White \"Doctorgt3\"]
[Black \"socal_dave\"]
[Result \"1-0\"]
[WhiteElo \"1267\"]
[BlackElo \"1240\"]
[TimeControl \"120+1\"]
[EndTime \"21:34:27 PDT\"]
[Termination \"Doctorgt3 won by resignation\"]
[ECO \"C31\"]
1. e4 e5 2. f4 d5 3. Nc3 c6 4. d4 exf4 5. Bxf4 Nf6 6. Bxb8 Rxb8 7. e5 Nd7 8. Nf3  Bb4 9. Qd3 O-O 10. O-O-O b5 11. a3 Bxa3 12. bxa3 a5 13. Kd2 b4 14. axb4 Rxb4 15.  Be2 Nb6 16. Rb1 Nc4+ 17. Ke1 Nb2 18. Qe3 Bf5 19. Na2 Bxc2 20. Nxb4 Bxb1 21. Nxc6  Qb6 22. Ne7+ Kh8 23. Kf2 a4 24. Rxb1 1-0"
    }
}
```

500 Error:
```
{
    "data": {  "pgn": "[Event \"Live Chess\"]  [Site \"Chess.com\"]  [Date \"2021.03.18\"]  [Round \"-\"]  [White \"Doctorgt3\"]  [Black \"socal_dave\"]  [Result \"1-0\"]  [WhiteElo \"1267\"]  [BlackElo \"1240\"]  [TimeControl \"120+1\"]  [EndTime \"21:34:27 PDT\"]  [Termination \"Doctorgt3 won by resignation\"] [ECO \"C31\"] 1. e4 e5 2. f4 d5 3. Nc3 c6 4. d4 exf4 5. Bxf4 Nf6 6. Bxb8 Rxb8 7. e5 Nd7 8. Nf3  Bb4 9. Qd3 O-O 10. O-O-O b5 11. a3 Bxa3 12. bxa3 a5 13. Kd2 b4 14. axb4 Rxb4 15.  Be2 Nb6 16. Rb1 Nc4+ 17. Ke1 Nb2 18. Qe3 Bf5 19. Na2 Bxc2 20. Nxb4 Bxb1 21. Nxc6  Qb6 22. Ne7+ Kh8 23. Kf2 a4 24. Rxb1 1-0"
    }
}
```

### PR DESCRIPTION
**Pull request by dmcnulla**
Sorry, my IDE is set up to drop spaces at the end of lines and create one blank line at the end of files. It's a requirement for the work team I'm on.

Anyway, I tried this out. 
Request:
```
{
    "delimiter": "|",
    "data": {
        "pgn": "[Event \"Live Chess\"]|[Site \"Chess.com\"]|[Date \"2021.03.18\"]|[Round \"-\"]|[White \"Doctorgt3\"]|[Black \"socal_dave\"]|[Result \"1-0\"]|[WhiteElo \"1267\"]|[BlackElo \"1240\"]|[TimeControl \"120+1\"]|[EndTime \"21:34:27 PDT\"]|[Termination \"Doctorgt3 won by resignation\"]|[ECO \"C31\"]|1. e4 e5 2. f4 d5 3. Nc3 c6 4. d4 exf4 5. Bxf4 Nf6 6. Bxb8 Rxb8 7. e5 Nd7 8. Nf3  Bb4 9. Qd3 O-O 10. O-O-O b5 11. a3 Bxa3 12. bxa3 a5 13. Kd2 b4 14. axb4 Rxb4 15.  Be2 Nb6 16. Rb1 Nc4+ 17. Ke1 Nb2 18. Qe3 Bf5 19. Na2 Bxc2 20. Nxb4 Bxb1 21. Nxc6  Qb6 22. Ne7+ Kh8 23. Kf2 a4 24. Rxb1 1-0"
    }
}
```
Response:
```
"{\"status\": 200, \"message\": \"Games Successfully Parsed.\"}"
```

### CODE REVIEW

**Comment by edmundlam** [comment]
Hi @dmcnulla thanks for the PR. This is an old repo, but both of us are still alive and kicking :) No problem on the whitespace fixes.

Before adding a delimiter, did you test serializing the pgn with json.dumps() before posting it? This would escape the newlines which should then be loaded correctly with json.loads(). Note I haven't tested this myself yet, so I'm not sure if this will work. 

For example:

``` python
pgn = """
[Event "State Ch."]
[Site "New York, USA"]
[Date "1910.??.??"]
[Round "?"]
[White "Capablanca"]
[Black "Jaffe"]
[Result "1-0"]
[ECO "D46"]
[Opening "Queen's Gambit Dec."]
[Annotator "Reinfeld, Fred"]
[WhiteTitle "GM"]
[WhiteCountry "Cuba"]
[BlackCountry "United States"]

1. d4 d5 2. Nf3 Nf6 3. e3 c6 4. c4 e6 5. Nc3 Nbd7 6. Bd3 Bd6
7. O-O O-O 8. e4 dxe4 9. Nxe4 Nxe4 10. Bxe4 Nf6 11. Bc2 h6
12. b3 b6 13. Bb2 Bb7 14. Qd3 g6 15. Rae1 Nh5 16. Bc1 Kg7
17. Rxe6 Nf6 18. Ne5 c5 19. Bxh6+ Kxh6 20. Nxf7+ 1-0
"""

serialized_pgn = json.dumps(pgn)
serialized_pgn

""" outputs
'"\\n[Event \\"State Ch.\\"]\\n[Site \\"New York, USA\\"]\\n[Date \\"1910.??.??\\"]\\n[Round \\"?\\"]\\n[White \\"Capablanca\\"]\\n[Black \\"Jaffe\\"]\\n[Result \\"1-0\\"]\\n[ECO \\"D46\\"]\\n[Opening \\"Queen\'s Gambit Dec.\\"]\\n[Annotator \\"Reinfeld, Fred\\"]\\n[WhiteTitle \\"GM\\"]\\n[WhiteCountry \\"Cuba\\"]\\n[BlackCountry \\"United States\\"]\\n\\n1. d4 d5 2. Nf3 Nf6 3. e3 c6 4. c4 e6 5. Nc3 Nbd7 6. Bd3 Bd6\\n7. O-O O-O 8. e4 dxe4 9. Nxe4 Nxe4 10. Bxe4 Nf6 11. Bc2 h6\\n12. b3 b6 13. Bb2 Bb7 14. Qd3 g6 15. Rae1 Nh5 16. Bc1 Kg7\\n17. Rxe6 Nf6 18. Ne5 c5 19. Bxh6+ Kxh6 20. Nxf7+ 1-0\\n"'
"""
```

We can definitely add a test + update docs if this is how it has to be passed in.

**Comment by dmcnulla** [comment]
I was using postman at the time.  I introduced an issue for get, but didn’t catch that until after I imported games with the client I wrote. I changed the  PR. Then I saw this email! I’ll try your suggestion, which sounds like it would work.

Thanks!

**Comment by prateeksan** [comment]
@dmcnulla thanks for contributing anyway! Feel free to push more PRs :)

**Comment by dmcnulla** [comment]
OK, I was able to create a good post to the server running on the master
branch. Here is the body. I had to use one double-quote-set around the pgn,
single quotes for the tag values, and the entire pgn in one line.
{
"data": {
"pgn": "[Event 'State Ch.']\n[Site 'New York, USA']\n[Date
'1910.??.??']\n[Round '?']\n[White 'Capablanca']\n[Black 'Jaffe']\n[Result
'1-0']\n[ECO 'D46']\n[Opening 'Queen's Gambit Dec.']\n[Annotator 'Reinfeld,
Fred']\n[WhiteTitle 'GM']\n[WhiteCountry 'Cuba']\n[BlackCountry 'United
States']\n[WhiteElo '']\n[BlackElo '']\n\n1. d4 d5 2. Nf3 Nf6 3. e3 c6 4.
c4 e6 5. Nc3 Nbd7 6. Bd3 Bd6\n7. O-O O-O 8. e4 dxe4 9. Nxe4 Nxe4 10. Bxe4
Nf6 11. Bc2 h6\n12. b3 b6 13. Bb2 Bb7 14. Qd3 g6 15. Rae1 Nh5 16. Bc1
Kg7\n17. Rxe6 Nf6 18. Ne5 c5 19. Bxh6+ Kxh6 20. Nxf7+ 1-0"
}
}

Here is a second example with two games in it:
{
"data": {
"pgn": "[Event 'Live Chess']\n[Site 'Chess.com']\n[Date
'2021.01.28']\n[Round '-']\n[White 'sxzhou']\n[Black 'socal_dave']\n[Result
'0-1']\n[WhiteElo '1172']\n[BlackElo '1216']\n[TimeControl
'120+1']\n[EndTime '22:00:36 PST']\n[Termination 'socal_dave won on
time']\n[ECO 'D00c']\n1. d4 d5 2. Bf4 Nf6 3. e3 e6 4. Nf3 c5 5. c3 c4 6. b3
b5 7. bxc4 bxc4 8. Be2 Be7 9. Nbd2 Ne4 10. Nxe4 dxe4 11. Ne5 f6 12. Nxc4
O-O 13. Nd2 f5 14. Be5 Ba6 15. Bxa6 Nxa6 16. O-O Bf6 17. Bg3 Bg5 18. Nb3 f4
19. exf4 Bxf4 20. Bxf4 Rxf4 21. Qe2 Nc7 22. Nc5 Qg5 23. Nxe4 Qg6 24. Ng3
Nd5 25. c4 Nc3 26. Qe5 Raf8 27. d5 exd5 28. Qxc3 dxc4 29. Rad1 Qa6 30. Rd7
Qxa2 31. Rd4 Rxf2 0-1\n\n[Event 'Live Chess']\n[Site 'Chess.com']\n[Date
'2021.01.28']\n[Round '-']\n[White 'KingCope45']\n[Black
'socal_dave']\n[Result '0-1']\n[WhiteElo '1210']\n[BlackElo
'1224']\n[TimeControl '120+1']\n[EndTime '23:02:59 PST']\n[Termination
'socal_dave won on time']\n[ECO 'C50a']\n1. e4 e5 2. Nf3 Nc6 3. Bc4 Nd4 4.
d3 Nxf3+ 5. Qxf3 Nf6 6. Bg5 Be7 7. Nc3 c6 8. b4 d6 9. b5 O-O 10. bxc6 bxc6
11. Rb1 Bd7 12. O-O Ne8 13. Rb7 Bxg5 14. Rfb1 Nc7 15. g3 d5 16. exd5 cxd5
17. Nxd5 Bc6 18. Rxc7 Bxd5 19. Bxd5 Qxc7 20. Bxa8 Qxc2 21. Rb7 Qxa2 22. Qf5
Bf6 23. Qd7 Qe6 24. Qc7 Qh3 25. Rb8 Qe6 26. Rxf8+ Kxf8 27. Qb8+ Qe8 28.
Qd6+ Be7 0-1"
}
}

It might be good to have a test with the entire body as an example what it
ought to look like, or maybe a curl example in the README? I'm closing my
PR for good now that I have it sussed out.

BTW, here is my client (still work in progress):
https://github.com/dmcnulla/chesspi_client
***@***.***:dmcnulla/chesspi_client.git

Thanks,

Dave McNulla

**Pull request closed without merging**
